### ISSUE TITLE
DuckDuckGo searchbar always redirect to duckduckgo.com/search

### ISSUE THREAD

**Issue by DiogoBnfr** [lookingcoolonavespa/Ether#1]
I like to use browser with minimum mouse usage, so I press "tab" two times everytime I open a new tab to select the searchbar in my Ether, but, when I search for something, it always redirect me to a DuckDuckGo page (Adress: https://duckduckgo.com/search?q=bla&ia=web) with the searchbar filled with "search". So I need to press "/", erase the text and search again for what I really want. Not a big problem at all, but turns annoying when you need to be constantly doing searchs. By the way, I never had problems when searching with Google.

**Comment by lookingcoolonavespa** [comment]
Just pushed out a fix. Thanks for bringing this up
