### ISSUE TITLE
Copy current config to clipboard doesn't work.

### ISSUE THREAD

**Issue by qmatic0** [lookingcoolonavespa/Ether#2]
When clicking "Copy current config to clipboard" it doesn't copy anything.

**Comment by lookingcoolonavespa** [comment]
I'm unable to recreate this on my end. Can you post a screenshot of the console tab of your browser's dev tools? eg. [console.jpg](https://postimg.cc/SjK1PGx1)

**Comment by qmatic0** [comment]
Sorry for the late reply. Here's my console: https://imgur.com/a/0Y199hu

Hope it helps!

**Comment by lookingcoolonavespa** [comment]
Thank you for the screen. Unfortunately I'm unable to diagnose the issue based on the screenshot. Would you be able to type `localStorage` into your console and post a screenshot of the expanded results? eg. [localStorage.jpg](https://i.postimg.cc/DZrpKy0x/local-Storage.jpg) 
Also does `honey:core-sdk:*` ring any bells?

**Comment by qmatic0** [comment]
Here's my console with the localstorage command: https://imgur.com/a/cw8YUMK

As for honey:core-sdk, I really have no idea what that is. The only thing I can think of is the [honey extension](https://chrome.google.com/webstore/detail/honey-automatic-coupons-r/bmnlcjabgnpnenekpadlanbbkooimhnj) I have installed but I tried disabling it (and even all extensions) and the results were the same.

Upon further testing, starting my browser (edge) in incognito mode and loading the start page with default settings and links allowed the current config to be copied. It seems to have something to do with me changing the links because that's all I've pretty much done besides switching themes around.

Hope this helps!

**Comment by lookingcoolonavespa** [comment]
If you type ```localStorage.removeItem("debug")``` into your console and hit Enter, it should allow you to copy the config. If it doesn't please expand the results of `localStorage` and post the results. 

I think an extension is injecting javascript into the web page and somehow saving an illegal value into localStorage.

**Comment by qmatic0** [comment]
Using localStorage.removeItem("debug") did indeed work!

**Comment by lookingcoolonavespa** [comment]
Cool I pushed a fix
